### ISSUE TITLE
Merge michitux' fork

### ISSUE THREAD

**Issue by p3732** [stamatak/terraces#2]
@michitux Please :-)
(I can not create issues on the fork, that is why I created one here, sorry about that)

**Comment by michitux** [comment]
The changes from my fork have been incorporated into the main repository afaik.

**Comment by stamatak** [comment]
but what is your issue about?

**Comment by p3732** [comment]
Okay, it was not clear from the overview under 'fork' that all changes are incorporated already, as there isn't any commit to indicate it. We just wanted to make sure we work on the most current version, thanks!
Closing.
